- name: Развёртывание мониторинга и логов в контейнерах
  hosts: localhost
  become: true

  tasks:
    - name: Копировать docker-compose и конфиги
      copy:
        src: ./monitoring
        dest: /opt/

    - name: Запустить мониторинг
      shell: |
        touch -p /var/log/containers.log
        chmod 777 /var/log/containers.log
        cd /opt/monitoring/files
        docoker network create monitoring
        docker-compose up -d
