- name: Развёртывание мониторинга и логов в контейнерах
  hosts: localhost
  become: true

  tasks:
    - name: Копировать docker-compose и конфиги
      synchronize:
        src: ./monitoring/
        dest: /opt/monitoring/
        recursive: yes

    # - name: Собрать Fluentd образ (с Prometheus-плагином)
    #   docker_image:
    #     name: fluentd-custom
    #     source: build
    #     build:
    #       path: /opt/monitoring/fluentd/
    #     tag: latest

    - name: Запустить мониторинг
      shell: |
        cd /opt/monitoring/files
        docker-compose up -d
