- name: Развёртывание мониторинга и логов в контейнерах
  hosts: localhost
  become: true

  tasks:
    - name: Копировать docker-compose и конфиги
      copy:
        src: ./monitoring
        dest: /opt/

    - name: Запустить мониторинг
      shell: |
        mkdir -p /var/log/logstash 
        chown -R 1000:1000 /var/log/logstash
        cd /opt/monitoring/files
        docker network create monitoring
        docker-compose up -d
