- name: Развёртывание мониторинга и логов в контейнерах
  hosts: localhost
  become: true

  tasks:
    - name: Копировать docker-compose и конфиги
      copy:
        src: ./monitoring
        dest: /opt/

    - name: Запустить мониторинг
      shell: |
        cd /opt/monitoring/files
        docker-compose up -d
