- name: Развёртывание мониторинга и логов в контейнерах
  hosts: localhost
  become: true

  tasks:
    - name: Копировать docker-compose и конфиги
      copy:
        src: ./monitoring
        dest: /opt/

    - name: Запустить мониторинг
      shell: |
        mkdir /opt/monitoring/fluentd/logs
        chmod 777 /opt/monitoring/fluentd/logs
        cd /opt/monitoring/files
        docoker network create monitoring
        docker-compose up -d
