- name: Развёртывание мониторинга и логов в контейнерах
  hosts: localhost
  become: true

  tasks:
    - name: Копировать docker-compose и конфиги
      copy:
        src: ./monitoring
        dest: /opt/

    - name: Создать для логов
      ansible.builtin.file:
        path: /opt/monitoring/fluentd/log
        state: directory
        owner: 1000  # Владелец — fluent
        group: 1000  # Группа — fluent (можно оставить как есть, например, root)
        mode: '0700' 

    - name: Запустить мониторинг
      shell: |
        cd /opt/monitoring/files
        docker-compose up -d
