global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash:9600']
  
  - job_name: 'other_containers'
    static_configs:
      - targets: ['other-container:8080']