services:
  fluentd:
    image: sajac/fluentd
    container_name: fluentd
    ports:
      - "24231:24231"       
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/fluentd/log
    environment:
      - FLUENTD_CONF=fluent.conf
    networks:
      - monitoring
  prometheus:
    image: bitnami/prometheus:3.5.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:12.1.0
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
