services:
  fluentd:
    image: sajac/fluentd
    container_name: fluentd
    ports:
      - "24231:24231"       
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/fluentd/log
    environment:
      - FLUENTD_CONF=fluent.conf
    networks:
      - monitoring
  prometheus:
    image: ubuntu/prometheus:latest
    volumes:
      - ./prometheus.yml:/opt/config/prometheus.yml
    command:
      - '--config.file=/opt/config/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
