services:
  fluentd:
    image: fluent/fluentd:v1.16-1
    container_name: fluentd
    restart: unless-stopped
    privileged: true
    user: root
    networks:
      - monitoring
    ports:  
      - "24220:24220"     
    volumes:
      - /opt/monitoring/fluentd/conf:/fluentd/etc
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /opt/monitoring/fluentd/logs:/var/log 
    environment:
      - FLUENTD_CONF=fluent.conf
 
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring
    depends_on: 
    - fluentd
    ports:
    - "9090:9090"   
    volumes:
      - /opt/monitoring/prometheus.yml:/opt/config/prometheus.yml
    command:
      - '--config.file=/opt/config/prometheus.yml'
 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
    - prometheus
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    external: true