services:
  logstash:
    image: logstash:9.0.4
    container_name: logstasha
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - /opt/monitoring/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /opt/monitoring/logstash/pipeline.conf:/usr/share/logstash/pipeline
      - /var/log/logstash:/var/log/logstash
    ports:
      - "5044:5044"   # Для Beats input (если нужно)
      - "9600:9600"    # Logstash API
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring
    depends_on: 
    - logstash
    ports:
    - "9090:9090"   
    volumes:
      - /opt/monitoring/prometheus.yml:/opt/config/prometheus.yml
    command:
      - '--config.file=/opt/config/prometheus.yml'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
        tag: "{{.Name}}"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
    - prometheus
    ports:
      - "3000:3000"
    networks:
      - monitoring
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
        tag: "{{.Name}}"

networks:
  monitoring:
    external: true