services:
  fluentd:
    image: sajac/fluentd
    container_name: fluentd
    restart: unless-stopped
    ports:  
      - "24220:24220"     
    volumes:
      - /opt/monitoring/fluentd/conf:/fluentd/etc
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/monitoring/fluentd/log:/var/log/
    environment:
      - FLUENTD_CONF=fluent.conf
    networks:
      - monitoring
 
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    depends_on: 
    - fluentd
    ports:
    - "9090:9090"   
    volumes:
      - /opt/monitoring/prometheus.yml:/opt/config/prometheus.yml
    command:
      - '--config.file=/opt/config/prometheus.yml'
    networks:
      - monitoring
 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
    - prometheus
    ports:
      - "3000:3000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge