services:
  fluentd:
    image: sajac/fluentd
    container_name: fluentd
    restart: unless-stopped
    networks:
      - monitoring
    ports:  
      - "24220:24220"     
    volumes:
      - /opt/monitoring/fluentd/conf:/fluentd/etc
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/monitoring/fluentd/log:/var/log/
    environment:
      - FLUENTD_CONF=fluent.conf
 
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring
    depends_on: 
    - fluentd
    ports:
    - "9090:9090"   
    volumes:
      - /opt/monitoring/prometheus.yml:/opt/config/prometheus.yml
    command:
      - '--config.file=/opt/config/prometheus.yml'

    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        tag: docker.prometheus
 
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
    - prometheus
    ports:
      - "3000:3000"
    networks:
      - monitoring
    logging:
      driver: fluentd
      options:
        fluentd-address: fluentd:24224
        tag: docker.grafana

networks:
  monitoring:
    driver: bridge